[tool.poetry]
name = "indexify-extractor-sdk"
version = "0.0.16"
description = ""
authors = ["Diptanu Gon Choudhury <diptanu@tensorlake.ai>"]
readme = "README.md"


[tool.poetry.scripts]
indexify-extractor = "indexify_extractor_sdk.main:typer_app"

[tool.poetry.dependencies]
python = "^3.12"
typer = {extras = ["all"], version = "^0.9.0"}
pydantic = "^2.6.1"
langchain = "^0.1.5"
transformers = "^4.37.2"
torch = "^2.2.0"
fastapi = "^0.109.2"
nanoid = "^2.0.0"
grpcio = "^1.60.1"
uvicorn = "^0.27.0.post1"
protobuf = "^4.25.2"
pypdf = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
